name: Python CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies (+ JAX cpu version)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir .[dev]

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest -v --junitxml=junit/test-results.xml
